### ISSUE TITLE
Odd behavior of `Alternative` on Parsers?

### ISSUE THREAD

**Issue by hasufell** [composewell/streamly#1294] opened 2021-10-21 14:34 UTC
```hs
parseD (satisfy (== 1) <|> fromPure 2) (fromList [])
```

will raise:

```
*** Exception: ParseError "satisfy: end of input"
```

One has to write this to fix it:

```hs
parseD (((const 2) <$> eof) <|> satisfy (== 1) <|> fromPure 2) (fromList [])
```

which I consider rather odd.

Edit: https://github.com/composewell/streamly/issues/604

**Comment by harendra-kumar** [comment] 2021-11-24 11:09
This is a duplicate of #604, let's keep that one for tracking.

**Closed by harendra-kumar** 2021-11-24 11:09 UTC
Labels: disposition:duplicate, aspect:folds
