### ISSUE TITLE
nested-concurrent/parallely/toListSome benchmark crashes

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly#374] opened 2020-01-16 09:59 UTC
With this error:

```
benchmarking parallely/toListSome ... nested-concurrent: thread blocked indefinitely in an MVar operation
```

**Comment by shlok** [comment] 2023-05-10 09:47
@harendra-kumar Should this be closed as a duplicate of https://github.com/composewell/streamly/issues/551?

**Closed** 2024-01-12 07:36 UTC
Labels: type:bug, aspect:streams
