### ISSUE TITLE
Primitive-0.7.1

### ISSUE THREAD

**Issue by adamConnerSax** [composewell/streamly#562] opened 2020-06-25 21:43 UTC
the new version of primitive, allowed by the bounds in streamly, makes streamly fail to compile because of duplicate NFdata instances for Array.

**Comment by RyanGlScott** [comment] 2020-06-26 11:32
In particular, this is the build error that results from building `streamly-0.7.2` with `primitive-0.7.1`:

```
[56 of 71] Compiling Streamly.Internal.Data.Array ( src/Streamly/Internal/Data/Array.hs, dist/build/Streamly/Internal/Data/Array.o, dist/build/Streamly/Internal/Data/Array.dyn_o )

src/Streamly/Internal/Data/Array.hs:163:10: error:
    Duplicate instance declarations:
      instance NFData a => NFData (Array a)
        -- Defined at src/Streamly/Internal/Data/Array.hs:163:10
      instance NFData a => NFData (Array a)
        -- Defined in ‘Data.Primitive.Array’
    |
163 | instance NFData a => NFData (Array a) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by harendra-kumar** [comment] 2020-06-26 11:57
Thanks for raising the issue and the error details.

I guess, we need to do the following under CPP conditionals:

* remove the NFData instance as it is now available in `primitive`. 
* remove `{-# OPTIONS_GHC -fno-warn-orphans #-} ` as this may no longer be needed

Two points to consider:

1. `primitive`s new NFData instance does not have an INLINE pragma which means performance benchmarks may show regression because of rnf not getting inlined. This usually makes a big difference in benchmarking.
2. Should we upload `streamly-0.7.3` after fixing this and/or change the version bounds of primitive in the existing release on Hackage?

**Comment by adithyaov** [comment] 2020-06-26 12:20
> Should we upload streamly-0.7.3 after fixing this and/or change the version bounds of primitive in the existing release on Hackage?

We should probably change the version bounds on Hackage, to begin with.

**Comment by hasufell** [comment] 2020-06-26 13:54
Yes, version bounds should be fixed ASAP. Thats what revisions are for. https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md

Proper fix can take more time.

**Comment by pranaysashank** [comment] 2020-06-26 16:02
New revisions for streamly 0.7.1 and 0.7.2 are released that fix the version bounds.

**Comment by adithyaov** [comment] 2020-07-14 14:23
There are new revisions for `streamly-0.7.1` and `streamly-0.7.2`
#565 Solves the issue for any future version

**Closed by adithyaov** 2020-07-14 14:23 UTC
